############################################################
# velocity
############################################################
%YAML 1.2
---
VERSION: alpha.3  # Major.Minor update this when needed (git commit added on to end for bugfixes)
SYSTEM: x86_64
BACKEND: podman
DISTRO: centos
IMAGE_DIRECTORY: images
BUILD_DIRECTORY: /tmp/velocity/build
